#!/bin/sh
set -e

fail() {
    echo $1 >&2
    echo "usage: $0 [USER] [PASSWORD]" >&2
    exit 1
}

[[ -z $1 ]] && fail "Argument USER is missing."
[[ -z $2 ]] && fail "Argument PASSWORD is missing."

[[ ! -f /etc/seedbox/users ]] && touch /etc/seedbox/users
htpasswd -db /etc/seedbox/users $1 $2
