#!/bin/sh
set -e

# Check environment

fail() {
    echo 1>&2 "$1"
    echo 1>&2 "Usage: $(basename "$0") [LOGIN]"
    exit 1
}

if [ -z "$1" ] ; then
    fail "Argument \"LOGIN\" is missing."
fi

# Remove user

userdel "$1"
