#!/bin/sh
set -eu

# Check environment

fail() {
    echo "$1" 1>&2
    echo "Usage: $(basename "$0") [LOGIN]" 1>&2
    exit 1
}

if [ -z "$1" ] ; then
    fail "Argument \"LOGIN\" is missing."
fi

# Remove user

userdel "$1"
