version: "3"

services:
    aria2:
        command:
            - "aria2c"
            - "--dir=/var/lib/seedbox"
            - "--enable-dht=false"
            - "--enable-rpc"
            - "--log=-"
            - "--log-level=notice"
            - "--max-concurrent-downloads=10"
            - "--quiet"
            - "--rpc-listen-all=true"
            - "--rpc-secret=${RPC_SECRET}"
            - "--rpc-save-upload-metadata=false"
        environment:
            - "USER=nobody"
        image: timonier/aria2:latest
        ports:
            - "6800:6800"
        volumes:
            - "data:/var/lib/seedbox:rw"

    cakebox:
        environment:
            - "CAKEBOX_ACCESS=/cakebox/access/"
            - "CAKEBOX_ROOT=/var/lib/seedbox"
            - "CAKEBOX_USER=nobody"
            - "DIRECTORY_IGNORE=/(\\.aria2)$$/"
            - "RIGHTS_CAN_DELETE=TRUE"
        image: timonier/cakebox:latest
        volumes:
            - "data:/var/lib/seedbox:rw"

    seedbox:
        environment:
            - "SEEDBOX_USER=nobody"
        image: mauchede/seedbox:latest
        ports:
            - "22:22"
            - "80:80"
        volumes:
            - "config:/etc/seedbox:rw"
            - "data:/var/lib/seedbox:rw"

    webui-aria2:
        environment:
            - "RPC_HOST=127.0.0.1"
            - "RPC_SECRET=${RPC_SECRET}"
        image: timonier/webui-aria2:latest

volumes:
    config: {}
    data: {}
