#!/bin/sh
set -e

fail() {
    echo $1 >&2
    echo "$0 [USER]" >&2
    exit 1
}

[[ -z $1 ]] && fail "Argument USER is missing."

[[ ! -f /etc/seedbox/users ]] && touch /etc/seedbox/users
sed -i "/^$1:/ d" /etc/seedbox/users
